/**
 * This class is generated by jOOQ
 */
package com.evry.demo.entity.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestRecord extends org.jooq.impl.UpdatableRecordImpl<com.evry.demo.entity.tables.records.TestRecord> implements org.jooq.Record2<java.math.BigDecimal, java.lang.String> {

	private static final long serialVersionUID = 275884977;

	/**
	 * Setter for <code>PMTDATA.TEST.ID</code>.
	 */
	public void setId(java.math.BigDecimal value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PMTDATA.TEST.ID</code>.
	 */
	public java.math.BigDecimal getId() {
		return (java.math.BigDecimal) getValue(0);
	}

	/**
	 * Setter for <code>PMTDATA.TEST.TEKST</code>.
	 */
	public void setTekst(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PMTDATA.TEST.TEKST</code>.
	 */
	public java.lang.String getTekst() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.math.BigDecimal> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.math.BigDecimal, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.math.BigDecimal, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field1() {
		return com.evry.demo.entity.tables.Test.TEST.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.evry.demo.entity.tables.Test.TEST.TEKST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTekst();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestRecord value1(java.math.BigDecimal value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestRecord value2(java.lang.String value) {
		setTekst(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestRecord values(java.math.BigDecimal value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TestRecord
	 */
	public TestRecord() {
		super(com.evry.demo.entity.tables.Test.TEST);
	}

	/**
	 * Create a detached, initialised TestRecord
	 */
	public TestRecord(java.math.BigDecimal id, java.lang.String tekst) {
		super(com.evry.demo.entity.tables.Test.TEST);

		setValue(0, id);
		setValue(1, tekst);
	}
}
