/**
 * This class is generated by jOOQ
 */
package com.evry.demo.entity.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends org.jooq.impl.TableImpl<com.evry.demo.entity.tables.records.TestRecord> {

	private static final long serialVersionUID = 1516340767;

	/**
	 * The reference instance of <code>PMTDATA.TEST</code>
	 */
	public static final com.evry.demo.entity.tables.Test TEST = new com.evry.demo.entity.tables.Test();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.evry.demo.entity.tables.records.TestRecord> getRecordType() {
		return com.evry.demo.entity.tables.records.TestRecord.class;
	}

	/**
	 * The column <code>PMTDATA.TEST.ID</code>.
	 */
	public final org.jooq.TableField<com.evry.demo.entity.tables.records.TestRecord, java.math.BigDecimal> ID = createField("ID", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

	/**
	 * The column <code>PMTDATA.TEST.TEKST</code>.
	 */
	public final org.jooq.TableField<com.evry.demo.entity.tables.records.TestRecord, java.lang.String> TEKST = createField("TEKST", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

	/**
	 * Create a <code>PMTDATA.TEST</code> table reference
	 */
	public Test() {
		this("TEST", null);
	}

	/**
	 * Create an aliased <code>PMTDATA.TEST</code> table reference
	 */
	public Test(java.lang.String alias) {
		this(alias, com.evry.demo.entity.tables.Test.TEST);
	}

	private Test(java.lang.String alias, org.jooq.Table<com.evry.demo.entity.tables.records.TestRecord> aliased) {
		this(alias, aliased, null);
	}

	private Test(java.lang.String alias, org.jooq.Table<com.evry.demo.entity.tables.records.TestRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.evry.demo.entity.Pmtdata.PMTDATA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.evry.demo.entity.tables.records.TestRecord> getPrimaryKey() {
		return com.evry.demo.entity.Keys.SYS_C0011440;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.evry.demo.entity.tables.records.TestRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.evry.demo.entity.tables.records.TestRecord>>asList(com.evry.demo.entity.Keys.SYS_C0011440);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.evry.demo.entity.tables.Test as(java.lang.String alias) {
		return new com.evry.demo.entity.tables.Test(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.evry.demo.entity.tables.Test rename(java.lang.String name) {
		return new com.evry.demo.entity.tables.Test(name, null);
	}
}
