/**
 * This class is generated by jOOQ
 */
package com.evry.demo.entity.packages.pmt_grant;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Granttoroles extends org.jooq.impl.AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = 1102492441;

	/**
	 * Create a new routine call instance
	 */
	public Granttoroles() {
		super("GRANTTOROLES", com.evry.demo.entity.Pmtdata.PMTDATA, com.evry.demo.entity.packages.PmtGrant.PMT_GRANT);
	}
}
