/**
 * This class is generated by jOOQ
 */
package com.evry.demo.entity;

/**
 * A class modelling foreign key relationships between tables of the <code>PMTDATA</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.evry.demo.entity.tables.records.CustomerRecord> SYS_C0011439 = UniqueKeys0.SYS_C0011439;
	public static final org.jooq.UniqueKey<com.evry.demo.entity.tables.records.TestRecord> SYS_C0011440 = UniqueKeys0.SYS_C0011440;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.evry.demo.entity.tables.records.CustomerRecord> SYS_C0011439 = createUniqueKey(com.evry.demo.entity.tables.Customer.CUSTOMER, com.evry.demo.entity.tables.Customer.CUSTOMER.ID);
		public static final org.jooq.UniqueKey<com.evry.demo.entity.tables.records.TestRecord> SYS_C0011440 = createUniqueKey(com.evry.demo.entity.tables.Test.TEST, com.evry.demo.entity.tables.Test.TEST.ID);
	}
}
