/**
 * This class is generated by jOOQ
 */
package com.evry.demo.entity;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pmtdata extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1066487941;

	/**
	 * The reference instance of <code>PMTDATA</code>
	 */
	public static final Pmtdata PMTDATA = new Pmtdata();

	/**
	 * No further instances allowed
	 */
	private Pmtdata() {
		super("PMTDATA");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.evry.demo.entity.tables.Customer.CUSTOMER,
			com.evry.demo.entity.tables.Test.TEST);
	}
}
