/**
 * This class is generated by jOOQ
 */
package com.evry.demo.entity;

/**
 * Convenience access to all tables in PMTDATA
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PMTDATA.CUSTOMER
	 */
	public static final com.evry.demo.entity.tables.Customer CUSTOMER = com.evry.demo.entity.tables.Customer.CUSTOMER;

	/**
	 * The table PMTDATA.TEST
	 */
	public static final com.evry.demo.entity.tables.Test TEST = com.evry.demo.entity.tables.Test.TEST;
}
